services:
  juicy-check:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_BACKEND_URL: ${VITE_BACKEND_URL}
    restart: unless-stopped
    ports:
      - "8010:8010"
    environment:
      - NODE_ENV=production